-- 001 (PostgreSQL): same tables and columns as ../001_initial.sql.
-- Timestamps stay ISO 8601 UTC text with a trailing Z so both backends share the queries;
-- floats are DOUBLE PRECISION (PostgreSQL REAL is only 4 bytes); the unique index on
-- lower(username) keeps usernames case-insensitive like SQLite's COLLATE NOCASE.

CREATE TABLE users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT    NOT NULL,
    password_hash TEXT    NOT NULL,
    created_at    TEXT    NOT NULL
);
CREATE UNIQUE INDEX idx_users_username_lower ON users (lower(username));

CREATE TABLE predictions (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at      TEXT    NOT NULL,
    task            TEXT    NOT NULL CHECK (task IN ('regression', 'classification')),
    model           TEXT    NOT NULL,
    input_json      TEXT    NOT NULL,
    predicted_value DOUBLE PRECISION,
    predicted_label TEXT,
    actual_value    DOUBLE PRECISION,
    runtime_ms      DOUBLE PRECISION,
    batch_id        TEXT
);
CREATE INDEX idx_predictions_user_time ON predictions (user_id, created_at);

CREATE TABLE training_runs (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at    TEXT    NOT NULL,
    trained_at    TEXT,
    target        TEXT,
    train_size    INTEGER,
    test_size     INTEGER,
    best_model    TEXT,
    total_seconds DOUBLE PRECISION
);

CREATE TABLE model_runs (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id                INTEGER NOT NULL REFERENCES training_runs(id) ON DELETE CASCADE,
    model                 TEXT    NOT NULL,
    label                 TEXT,
    r2                    DOUBLE PRECISION,
    mae                   DOUBLE PRECISION,
    mse                   DOUBLE PRECISION,
    rmse                  DOUBLE PRECISION,
    cv_r2_mean            DOUBLE PRECISION,
    cv_r2_std             DOUBLE PRECISION,
    train_seconds         DOUBLE PRECISION,
    predict_ms_per_sample DOUBLE PRECISION,
    n_nonzero_coef        INTEGER,
    n_coefficients        INTEGER,
    best_params_json      TEXT,
    is_best               INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX idx_model_runs_run ON model_runs (run_id);
